### ISSUE TITLE
List of suggestions #2

### ISSUE THREAD

**Issue by ProjectionWizard** [ProjectionWizard/projectionwizard.github.io#3]
UI CHANGES
- [x] Toggle between meter and feet (Customize option)
- [x] When there are multiple suggested projections, it would be nice to be able to hover over a name with the cursor and see a preview of the projection. (fixed for world maps with #7, equidistant projection are still missing this)
- [x] The dialog to copy the PROJ or WKT definition has a cancel button and an okay button. A single Close button would be enough. 
- [x] When one enters the extension in the numerical fields, it can happen that the selected area is entirely outside of the map. In this case it would be nice if the map changed such that the selected area becomes visible.
  - (@jwasilgeo comment) could consider using one of these Leaflet map methods perhaps: `fitBounds` or `flyToBounds`
- [x] 089º 19' 12'’, remove leading 0 for degrees
- [x] Add continuous `<canvas>` update and redrawing during leaflet `rectangle` shape dragging and individual vertex dragging. (see #4 and https://github.com/ProjectionWizard/projectionwizard.github.io/issues/3#issuecomment-521290955)
- [x] Add continuous output and extend inputs update during rectangle dragging and individual vertex dragging. (see #4 and https://github.com/ProjectionWizard/projectionwizard.github.io/issues/3#issuecomment-521290955)
- [x] For the Two-point equidistant, a closing parenthesis is missing. 
- [x] Try placing the "customize" and "help" buttons on better location. 
- [x] Show a preview maps for equidistant world projections
- [x] For regional equidistant projections, change a preview of the projection when hover over a name with the cursor
- [x] While dragging a node of the rectangle, sometimes the rectangle outline changes to orange, and sometimes it flickers between orange and blue.
- [x] It would be nice to be able to zoom in with a double click (which is a de facto standard for web maps).
- [x] Reduce the size of regional maps (especially square maps and portrait-format maps), because they are large when compared to world maps. 
- [x] Some preview projections captions have no spaces.
- [x] It is a bit hard to see hover functionality. A hint to user is needed so they know that they can somehow interact with the text. 
- [ ] User cannot pan the map over the rectangle.

**Comment by beuan** [comment]
- [x] While dragging a node of the rectangle, sometimes the rectangle outline changes to orange, and sometimes it flickers between orange and blue. 
- [x] It would be nice to be able to zoom in with a double click (which is a de facto standard for web maps).
@jgravois, any ideas? Thanks!

**Comment by beuan** [comment]
- [x] Add continuous `<canvas>` update and redrawing during leaflet `rectangle` shape dragging and individual vertex dragging. 
- [x] Add continuous output and extend inputs update during rectangle dragging and individual vertex dragging.

Currently in progress by @jwasilgeo on branch [`continuous-canvas-updates`](https://github.com/ProjectionWizard/projectionwizard.github.io/tree/continuous-canvas-updates), documented separately in issue #4, and available in PR #6.

**Comment by jgravois** [comment]
> it would be nice to be able to zoom in with a double click.

I can't remember why I overrode the default. 

I feel like it caused some conflict with drawing, but you're welcome to remove the property and see if everything else still works.

https://github.com/ProjectionWizard/projectionwizard.github.io/blob/master/map.js#L413

**Comment by beuan** [comment]
> I can't remember why I overrode the default.

I suspect you overwrote it because you tried to set double click to zoom on rectangle and it didn't work properly.

> I feel like it caused some conflict with drawing, but you're welcome to remove the property and see if everything else still works.
> 
> https://github.com/ProjectionWizard/projectionwizard.github.io/blob/master/map.js#L413

Thanks @jgravois! I will check it out and see how it works.

**Comment by beuan** [comment]
Most items on the list are resolved. The only remaining one is the conflict between map panning and rectangle dragging. I think there is no solution to have both. I will keep rectangle dragging for now.

Thank you, @jwasilgeo and @jgravois for your help!
